### ISSUE TITLE
Exporting to CSV/XML longitude is wrong in North America

### ISSUE THREAD

**Issue by sycophantic** [jonsowman/cusf-standalone-predictor#101]
I created the following prediction http://habhub.org/predict/#!/uuid=17c787f1e3ff5274c9c65a966501321288bcac69

and exported to CSV and XML, in order to get the correct longitude I need to subtract 360 from the value.
![balloon](https://f.cloud.github.com/assets/634076/378727/8c6d2080-a559-11e2-94f4-25f39680a518.png)

The CSV is here: http://pastebin.com/pheHw1wB

**Comment by danielrichman** [comment]
Proposed change:

``` diff
daniel@zepto:cusf-standalone-predictor$ git diff
diff --git a/pred_src/pred.c b/pred_src/pred.c
index 0633b1d..1089a1d 100644
--- a/pred_src/pred.c
+++ b/pred_src/pred.c
@@ -315,6 +315,10 @@ int main(int argc, const char *argv[]) {
 }

 void write_position(float lat, float lng, float alt, int timestamp) {
+    // the predictor uses 0<=lng<360; most other things expect -180<lng<=180
+    if (lng > 180)
+        lng -= 360;
+
     if (kml_file) {
         fprintf(kml_file, "%g,%g,%g\n", lng, lat, alt);
         if (ferror(kml_file)) {
```

Can anyone think of anything that might break if I do this? Have checked (read source; not yet tested) pred.js and predict.py

**Comment by sycophantic** [comment]
Briefly looking through the code I don't see anywhere this would break anything.

**Comment by danielrichman** [comment]
Deployed. http://habhub.org/predict
