### ISSUE TITLE
Automatically Determine Elevation with Google Maps API

### ISSUE THREAD

**Issue by yottalogical** [jonsowman/cusf-standalone-predictor#115]
Currently you have to figure out and input the elevation of the launch site manually. It would be very useful if this could be done automatically using the [Google Maps Elevation API](https://developers.google.com/maps/documentation/elevation/intro). I hope it's at least worth considering. Thanks!

**Comment by adamgreig** [comment]
The latest version of the predictor, [Tawhiri](https://github.com/cuspaceflight/tawhiri) does determine elevation using [Ruaumoko](https://github.com/cuspaceflight/ruaumoko), but it's not yet deployed to the main website...
