### ISSUE TITLE
AJAX Interface

### ISSUE THREAD

**Issue by jonsowman** [jonsowman/cusf-standalone-predictor#13]
After clicking "Run Prediction", the data request should be sent to the server and the client polls for status.json, which contains:
1) Progress on getting GFS data & when complete
2) Prediction started
3) Prediction complete (client then grabs CSV and displays it)

Client must verify "prediction_complete == true" before trying to get a CSV and display it (even for index.php?uuid= predictions)

**Comment by adamgreig** [comment]
done
