### ISSUE TITLE
'Terrain' view by default

### ISSUE THREAD

**Issue by simrun** [jonsowman/cusf-standalone-predictor#31]
Rationale:
1) Roads aren't a consideration in planning a balloon launch through the predictor, i.e. they are clutter and make it harder to focus on the trajectories
2) Terrain view nicely highlights urban areas which we can then seek to avoid

**Comment by jonsowman** [comment]
http://code.google.com/apis/maps/documentation/javascript/reference.html#MapTypeId

**Comment by jonsowman** [comment]
Map is terrain view by default closed by 3d2af0121c6e913b0986c551aec2726d5bd5294f
