### ISSUE TITLE
lockfiles/mutex

### ISSUE THREAD

**Issue by jonsowman** [jonsowman/cusf-standalone-predictor#4]
Put the lockfile system back in place so only one user can run the predictor at a time

**Comment by jonsowman** [comment]
or do SESSIONS or something to allow multiple users without screwing up

**Comment by jonsowman** [comment]
GRIB predictor running properly with mutex closed by d99da9a417436efa43cee4d3cbc5821ff322a1f0

**Comment by adamgreig** [comment]
predict.py checks for other running instances and dies if found now, closing
