### ISSUE TITLE
Error messages are not very verbose

### ISSUE THREAD

**Issue by adamgreig** [jonsowman/cusf-standalone-predictor#64]
When trying to create a prediction in the past, the error message is "The server rejected the submitted form data: Server couldn't make a model from the form data". Something more akin to "Can not run predictions for dates in the past" would be much more useful.

**Comment by jonsowman** [comment]
Making error messages given to the user upon hitting Run Prediction more verbose - closed by 841afa60fa2c54c1364c0d80f7182b6968fcbec9
