### ISSUE TITLE
signal.alarm to force clean up of stalled processes

### ISSUE THREAD

**Issue by danielrichman** [jonsowman/cusf-standalone-predictor#72]
Feature request/suggestion; maybe calling signal.alarm() at the top of the script with a large value would present the build up of stalled predictor processes.

**Comment by jonsowman** [comment]
This is a great idea, will try and get round to this at some point!

**Comment by danielrichman** [comment]
I was looking at predict.py on nessie; I think that if you have the python script daemonise itself by fork disassociate fork, then you can avoid using atd, its forked process and the extra `sh` process that it will use.

**Comment by jonsowman** [comment]
Done.
