### ISSUE TITLE
Predictor seems to have indigestion when dealing with negative longitude launch locations.

### ISSUE THREAD

**Issue by danielrichman** [jonsowman/cusf-standalone-predictor#77]
All longitudes seem to be converted to positive numbers in the range 0-360 rather than -180-180 asap, however it _seems_ that the initial launch location is not given this treatment. The predictor appears to sporadically select GFS files that do not contain the launch latitude and longitude randomly when the launch longitude is negative; i.e., sometimes it works and sometimes it does not. 
Haven't been able to pinpoint exactly what the problem in pred_src/ is yet though I have barely read any of it. I'm about to open a pull request with a hacky fix, though the real cause of the bug still exists.

**Comment by jonsowman** [comment]
Fixed
