### ISSUE TITLE
KML output has a blank leading line

### ISSUE THREAD

**Issue by adamgreig** [jonsowman/cusf-standalone-predictor#82]
and apparently this breaks the kml?

**Comment by eroomde** [comment]
Correct. Problem lies in kml.php line 146

``` php
$kmlOut = join("\n", $kml);
```

which clearly puts in the preceding \n. suggest swapping the arguments.

**Comment by jonsowman** [comment]
The problem mentioned by eroomde is neither the problem nor solution. Please see http://www.php.net/manual/en/function.implode.php.

Issue #82 is properly fixed in commit b91f9ffa7.

**Comment by eroomde** [comment]
This is why I shouldn't be allowed near PHP. Looks enough like Python to lull you into a trap. The only thing "clear" about my comment was its stupidity.
