### ISSUE TITLE
progress.json

### ISSUE THREAD

**Issue by landis** [jonsowman/cusf-standalone-predictor#88]
Trying to run from ubuntu 10.04 server - site comes up ok, creates the hash folder within preds/ - but then gets hung up.  Apache log states File does not exist: .......progress.json

I have installed pydap, numpy, simple-json - but was unable to find package "json".  also have installed "python-json" on system.  
Permissions on preds folder are 777.  Any Ideas?

**Comment by adamgreig** [comment]
What version of python are you running? What happens if you load a Python interpreter and run '''import json'''?

**Comment by adamgreig** [comment]
You could also try running the predict.py script manually to see what the error output is -- off the top of my head I can't remember the correct invocation but you could easily cause the PHP to spit out the command line it runs, then run it manually to check for any errors.

**Comment by landis** [comment]
Should of checked the import json. That threw no error (python2.7). On
a lark, ran the predict.py script as root, and it went past this
point, and wrote the flightplan.csv file, but then died at
wind_file_cache.c:284. I clearly have a permission problem causing the
progress.json error - any idea what could cause the wind...:248 error?

Thanks again,
Jim

On Mar 14, 2012, at 6:13 PM, Adam Greig
reply@reply.github.com
wrote:

**Comment by adamgreig** [comment]
That's really odd and probably indicates bad wind data output by the Python script (possibly remnants of old runs?) or other problems reading the wind data. You might want to fix the permission issue first and then rerun and see if that helps.
